**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [7]:
import numpy as np

#Масив зі списку [5, 15, 25, 35, 45]
print(np.array([5, 15, 25, 35, 45]))

#Масив з нулів розміром 7
print(np.zeros(7))

#Масив з одиниць розміром 6
print(np.ones(6))

#Масив з числами від 10 до 19 використовуючи np.arange()
print(np.arange(10, 20))

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [13]:
my_arr = np.array([12, 24, 36, 48, 60])

#Помножте всі елементи на 2
my_arr_2 = my_arr * 2
print(my_arr_2)

#Додайте до всіх елементів 10
my_arr_10 = my_arr + 10
print(my_arr_10)

#Піднесіть всі елементи до квадрату
my_arr_square = my_arr ** 2
print(my_arr_square)

#Обчисліть квадратний корінь з усіх елементів
my_arr_sqrt = np.sqrt(my_arr)
print(my_arr_sqrt)

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [23]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

#Середнє значення
print(np.mean(data))

#Мінімум
print(np.min(data))

#Максимум
print(np.max(data))

#Суму всіх елементів
print(np.sum(data))

45.42857142857143
18
79
318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [26]:
arr = np.array([15, 22, 35, 44, 58, 67])

#Перший елемент
print(arr[0])

#Останній елемент
print(arr[-1])

#Елементи з індексами 1 до 3
print(arr[1:4])

#Елементи більші за 40
print(arr[arr > 40])

15
67
[22 35 44]
[44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [41]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

# Виведіть форму (shape) матриці
print(matrix.shape)

# Виведіть перший рядок
print(matrix[0, :])

# Виведіть другу колонку
print(matrix[:, 1])

# Обчисліть суму всіх елементів
print(np.sum(matrix))

# Обчисліть середнє всіх елементів
print(np.mean(matrix))

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
