### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [33]:
import numpy as np

vector = np.random.rand(10)

print(vector)
print(vector.shape)

[0.42693791 0.71698669 0.89357753 0.7709972  0.09001302 0.53618392
 0.25211863 0.80127327 0.34478415 0.51483447]
(10,)


In [34]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])

print(matrix)
print(matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]]
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [38]:
#Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.

np.round(vector + 10, 2)

array([10.43, 10.72, 10.89, 10.77, 10.09, 10.54, 10.25, 10.8 , 10.34,
       10.51])

In [39]:
#Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.

matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [40]:
# Створіть новий вектор, який містить квадрат кожного vector без циклів

square_vector = vector**2

square_vector

array([0.18227598, 0.51406992, 0.7984808 , 0.59443668, 0.00810234,
       0.2874932 , 0.0635638 , 0.64203885, 0.11887611, 0.26505453])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [41]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [47]:
# Задані дві матриці A і Bрозмірностями 3x2 та 2х3.
# Виконайте їхнє множення, щоб отримати матрицю 2x2.
# Виведіть результуючу матрицю result_matrix на екран.

result_matrix = np.dot(B, A)

result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [50]:
# Заданий вектор C розмірністю 2х1.
# Подумайте спочатку, яку розмірність Ви отрмаєте,
# коли домножите result_matrix на вектор C і який результат буде.
# А потім виконайте множення і виведіть результат на екран.

np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

множення на вектор (0, 1) фактично залишило нам тільки другий стовпчик

In [51]:
# Задана матриця D розмірністю 2х2.
# Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите
# result_matrix на матрицю D і який результат буде.
# А потім виконайте множення і виведіть результат на екран.

np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

а в цьому заданні стовпчики помінялись місцями


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [52]:
#Транспонуйте result_matrix.

result_matrix_T = result_matrix.T

result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [55]:
# Зробіть транспонування вектора vector і виведіть форму нової структури. Чи бачите ви зміну?

vector_T = vector.T

print(vector_T)
print(vector_T.shape)


[0.42693791 0.71698669 0.89357753 0.7709972  0.09001302 0.53618392
 0.25211863 0.80127327 0.34478415 0.51483447]
(10,)


ні, зміни немає, бо це одновимірний вектор

In [57]:
# Використайте операцію numpy.expand_dims над вектором vector з аргументом axis=1.
# Запишіть отриманий результат в змінну column_vector і виведіть на екран. Порівняйте з vector.

column_vector = np.expand_dims(vector, axis=1)

print(vector, vector.shape)
print(column_vector, column_vector.shape)

[0.42693791 0.71698669 0.89357753 0.7709972  0.09001302 0.53618392
 0.25211863 0.80127327 0.34478415 0.51483447] (10,)
[[0.42693791]
 [0.71698669]
 [0.89357753]
 [0.7709972 ]
 [0.09001302]
 [0.53618392]
 [0.25211863]
 [0.80127327]
 [0.34478415]
 [0.51483447]] (10, 1)


vector - одновимірний вектор

column_vector - матриця розмірности (10,1)

In [58]:
# Зробіть транспонування column_vector, виведіть результат на екран разом з розмірностями отриманої структури.

print(column_vector.T)
print(column_vector.T.shape)

[[0.42693791 0.71698669 0.89357753 0.7709972  0.09001302 0.53618392
  0.25211863 0.80127327 0.34478415 0.51483447]]
(1, 10)


In [ ]:
тепер column_vector можна транспонувати і розмірність помінялась на (1, 10)